name: Sync gh-pages with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Needed to push changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get complete history for merging

      - name: Add upstream remote # CHANGE THE REPO WHEN MIGRATING THIS WORKFLOW
        run: |
          git remote add upstream https://github.com/electh/ReactFlux.git
          git fetch upstream

      - name: Merge upstream changes # CHANGE THE NAME OF THE BRANCH TWICE
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Ensure we checkout the correct branch
          git checkout origin/gh-pages
          git switch -c gh-pages  # Ensure it's a local branch

          # Try to merge - this will fail if there are conflicts
          git merge upstream/gh-pages --no-ff --no-edit --strategy-option=theirs

      - name: Push changes
        run: git push origin gh-pages # CHANGE THE NAME OF THE BRANCH
