name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to sync with upstream"
        required: false
        default: "main"  # Default to 'main' if not specified

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/electh/ReactFlux.git
          git fetch upstream

      - name: Merge upstream changes into selected branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          BRANCH="${{ github.event.inputs.branch || 'main' }}"  # Use input or default to 'main'

          git checkout $BRANCH
          git merge upstream/$BRANCH --no-ff --no-edit --strategy-option=theirs

      - name: Push changes
        run: |
          BRANCH="${{ github.event.inputs.branch || 'main' }}"
          git push origin $BRANCH
